export type Lang = "es" | "en";

// All visible copy for both languages. *word* is set in the italic serif.
export const COPY = {
  es: {
    skip: "Saltar al compositor de señales",
    loader: {
      top: ["Raúl Romero", "Lab 001 — Convergence", "Estrategia × Diseño × Tecnología"],
      calibrating: "Calibrando el campo",
      ready: "El sistema está listo.",
      withSound: "Entrar con sonido",
      silent: "Entrar en silencio",
      hint: "Mejor con auriculares · Desliza para converger",
    },
    hud: {
      motion: (calm: boolean) => `Movimiento: ${calm ? "calma" : "completo"}`,
      sound: (on: boolean) => `Sonido ${on ? "sí" : "no"}`,
      soundOn: "Activar sonido",
      soundOff: "Silenciar",
      language: "Idioma",
    },
    hints: {
      pointer: "Mantén pulsado para atraer · Suelta para dispersar · Arrastra para girar",
      touch: "Toca la materia para dispersarla",
    },
    chapters: ["Preludio", "Atención", "Forma", "Comportamiento", "Convergencia", "Producto"],
    hero: {
      meta: ["(Lab 001)", "Un estudio interactivo sobre lo que ocurre\ncuando tres disciplinas se vuelven un solo sistema.", "2026"],
      lede: "El marketing atrae la *atención*. El diseño le da *forma*. El desarrollo hace que *responda*.",
      cue: "Desliza para converger",
    },
    attention: {
      title: "Atención", discipline: "Marketing",
      statement: "La atención sin dirección es *ruido.*",
      body: "Todo producto empieza como interés disperso: miradas, clics, intenciones a medias. Por sí solo no va a ninguna parte. Mueve el cursor por el campo y mira cómo se reúne a tu alrededor. Esa atracción es la materia prima.",
      aside: ["Entrada · Señal sin estructura", "Mantén pulsado para atraer el campo"],
    },
    form: {
      title: "Forma", discipline: "Diseño",
      statement: "La estructura convierte la atención en *significado.*",
      body: "El diseño no es decoración. Es decidir dónde va cada cosa y por qué. La misma materia, ahora alineada en capas, retículas y jerarquía: algo que una persona entiende de un vistazo.",
      aside: ["Capas 05 · Retícula 12 col", "Arrastra para girar la estructura"],
    },
    behavior: {
      title: "Comportamiento", discipline: "Desarrollo",
      statement: "Las ideas se vuelven reales cuando pueden *responder.*",
      body: "El código le da pulso a la forma. La información empieza a moverse, a ramificarse y a reaccionar a quien la usa. Envía una señal a través del sistema.",
      aside: ["Entrada → Estado → Respuesta", "72 canales · 1 nodo"],
      action: "Enviar una señal",
    },
    marquee: ["Atención", "Forma", "Comportamiento"],
    convergence: {
      eyebrow: "Convergencia",
      statement: "El sistema se vuelve más que la suma de sus *partes.*",
      body: "Cuando las tres dejan de trabajar por turnos y empiezan a trabajar como una sola, el resultado no es una suma. Es un producto vivo.",
    },
    product: {
      eyebrow: "Producto",
      statement: "Tres entradas. Un sistema *vivo.*",
      body: "Enruta cada señal hacia el sistema. Cada disciplina enciende su propia órbita y el conjunto responde.",
      composer: "Compositor de señales",
      routedCount: "enrutadas",
      route: "Enrutar →",
      routed: "Enrutada",
      cursorRoute: "Enrutar",
      cursorRouted: "Hecho",
      reset: "Reiniciar",
      idle: "Selecciona una señal para enrutarla.",
      progress: (n: number) => `${n} de 6 señales enrutadas.`,
      complete: "Las seis señales enrutadas. Así se siente un sistema que funciona.",
      disciplines: ["Marketing", "Diseño", "Desarrollo"],
      signals: ["Aclarar la oferta", "Hacer visible la estructura", "Responder a la intención", "Ganar la primera mirada", "Mostrar el siguiente paso", "Eliminar la fricción"],
    },
    outro: {
      statement: "Lo interesante ocurre *entre* disciplinas.",
      start: "Empezar un proyecto",
      how: "Ver cómo trabajo",
      replay: "Repetir ↑",
      credits: ["Concepto, diseño y código — Raúl Romero", "WebGL · GLSL · Web Audio · 2026", "Volver a Labs"],
      home: "/",
    },
    cursor: { enter: "Entrar", begin: "Empezar", send: "Enviar", talk: "Hablemos", read: "Leer", again: "Otra vez", reset: "Reiniciar", labs: "Labs", motion: "Movimiento", sound: "Sonido", lang: "Idioma" },
  },
  en: {
    skip: "Skip to the signal composer",
    loader: {
      top: ["Raúl Romero", "Lab 001 — Convergence", "Strategy × Design × Technology"],
      calibrating: "Calibrating the field",
      ready: "The system is ready.",
      withSound: "Enter with sound",
      silent: "Enter in silence",
      hint: "Best with headphones · Scroll to converge",
    },
    hud: {
      motion: (calm: boolean) => `Motion: ${calm ? "calm" : "full"}`,
      sound: (on: boolean) => `Sound ${on ? "on" : "off"}`,
      soundOn: "Turn sound on",
      soundOff: "Mute sound",
      language: "Language",
    },
    hints: {
      pointer: "Hold to attract · Release to scatter · Drag to rotate",
      touch: "Tap the matter to scatter it",
    },
    chapters: ["Prelude", "Attention", "Form", "Behavior", "Convergence", "Product"],
    hero: {
      meta: ["(Lab 001)", "An interactive study of what happens\nwhen three disciplines become one system.", "2026"],
      lede: "Marketing brings *attention*. Design gives it *form*. Development makes it *behave*.",
      cue: "Scroll to converge",
    },
    attention: {
      title: "Attention", discipline: "Marketing",
      statement: "Attention without direction is *noise.*",
      body: "Every product begins as scattered interest: glances, clicks, half-intentions. On its own it goes nowhere. Move your cursor through the field and watch it gather around you. That pull is the raw material.",
      aside: ["Input · Unstructured signal", "Hold to pull the field in"],
    },
    form: {
      title: "Form", discipline: "Design",
      statement: "Structure turns attention into *meaning.*",
      body: "Design is not decoration. It is deciding where each thing goes, and why. The same matter, now aligned into layers, grids and hierarchy: something a person can read at a glance.",
      aside: ["Layers 05 · Grid 12 col", "Drag to turn the structure"],
    },
    behavior: {
      title: "Behavior", discipline: "Development",
      statement: "Ideas become real when they can *respond.*",
      body: "Code gives form a pulse. Information starts to move, branch and react to the people using it. Send a signal through the system.",
      aside: ["Input → State → Response", "72 channels · 1 node"],
      action: "Send a signal",
    },
    marquee: ["Attention", "Form", "Behavior"],
    convergence: {
      eyebrow: "Convergence",
      statement: "The system becomes more than its *parts.*",
      body: "When the three stop working in sequence and start working as one, the result is not a sum. It is a product that is alive.",
    },
    product: {
      eyebrow: "Product",
      statement: "Three inputs. One *living* system.",
      body: "Route each signal into the system. Every discipline lights its own orbit, and the whole responds.",
      composer: "Signal composer",
      routedCount: "routed",
      route: "Route →",
      routed: "Routed",
      cursorRoute: "Route",
      cursorRouted: "Done",
      reset: "Reset",
      idle: "Select a signal to route it.",
      progress: (n: number) => `${n} of 6 signals routed.`,
      complete: "All six signals routed. This is what a working system feels like.",
      disciplines: ["Marketing", "Design", "Development"],
      signals: ["Clarify the offer", "Make the structure visible", "Respond to intent", "Earn the first glance", "Reveal the next step", "Remove the friction"],
    },
    outro: {
      statement: "The interesting part happens *between* disciplines.",
      start: "Start a project",
      how: "See how I work",
      replay: "Replay ↑",
      credits: ["Concept, design & code — Raúl Romero", "WebGL · GLSL · Web Audio · 2026", "Back to Labs"],
      home: "/en",
    },
    cursor: { enter: "Enter", begin: "Begin", send: "Send", talk: "Talk", read: "Read", again: "Again", reset: "Reset", labs: "Labs", motion: "Motion", sound: "Sound", lang: "Language" },
  },
} as const;

export type Copy = (typeof COPY)[Lang];
